### ISSUE TITLE
OTC integration

### ISSUE THREAD

**Issue by czechdude** [Danielhiversen/pyOpenGarage#7]
Hi, 

have you considered also making it work with OTC? should be prety easy. Home Assistant unfortunately does not accept the OTC proxy adress with the token:(

extract from the api doc:

![image](https://github.com/Danielhiversen/pyOpenGarage/assets/601761/a58d5642-8d66-4a33-8855-e37509096a62)

thanks for your consideration

**Comment by Danielhiversen** [comment]
No plans to add that, but any contributions are welcome

**Comment by czechdude** [comment]
Actually it works, what needed a little tweaking was Home Assistant integration, that I needed to customize, so I might actually make a contribution to hassio repo.
